import type { Metadata } from 'next';


export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function NewsLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (

		<div style={{ border: '1px solid blue' }}>
			{children}
		</div>

	);
}
